apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: postgres-operator
  labels:
    app: postgres-exporter
spec:
  selector:
    postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187

