apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporters
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  namespaceSelector:
    matchNames:
      - postgres-operator
  endpoints:
  - port: metrics
    interval: 30s

